### ISSUE TITLE
Issue with ROI if using extra classes

### ISSUE THREAD

**Issue by JanaJarecki** [FlorianSchwendinger/ROI_docs#4]
Hi Florian!

first of all: this comment needs migration to the ROI repository but I could not find a ROI repo on github (my bad! Apologies.).

ROI has a small bug if an own class is prepended to a constraint. Minimal working example is below. I think it would be good if the code would be robust in its method dispatch. Especially because I really do envision the ROI package to be used in many other packages in the future.

**The issue**

The error message that we expect in the below case is the informative `Error in (function (x, solver, control = list(), ...)  :                                 
  no solver found for this signature:` but instead with an added class we get the rather confusing error `        
Error in `colnames<-`(`*tmp*`, value = available_types()) :                              
  Versuch die 'colnames' für ein Objekt mit weniger als zwei Dimensionen zu setzen` 

**Working example**

```r
    n <- 3
    const <- ROI::L_constraint(rbind(c(1,1,0)), rhs = 2, dir = "==", names = letters[1:3])

    class(const) <- c("new", class(const)) # <---- this messes it up

    bounds <- ROI::V_bound(
            li = seq_len(n), lb = c(0,0,0),
            ui = seq_len(n), ub = c(1,1,20)
            )

    objective <- ROI::F_objective(
            F = function(par) par[1] * par[2] * par[3],
            n = n
            )

    problem <- ROI::OP(
            objective = objective,
            constraints = const,
            bounds = bounds
          )

    sol <- do.call(
            what = ROI::ROI_solve,
            args = c(list(
              x = problem,
              solver = "auto",
              start = c(0,0,0))
          ), envir = parent.frame())
```

**sessionInfo()**

    R version 4.0.2 (2020-06-22)                                                             
    Platform: x86_64-w64-mingw32/x64 (64-bit)                                                
    Running under: Windows 10 x64 (build 18363)                                              
                                                                                             
    Matrix products: default                                                                 
                                                                                             
    locale:                                                                                  
    [1] LC_COLLATE=German_Switzerland.1252  LC_CTYPE=German_Switzerland.1252                 
    [3] LC_MONETARY=German_Switzerland.1252 LC_NUMERIC=C                                     
    [5] LC_TIME=German_Switzerland.1252                                                      
                                                                                             
    attached base packages:                                                                  
    [1] stats     graphics  grDevices utils     datasets  methods   base                     
                                                                                             
    other attached packages:                                                                 
    [1] ROI_0.3-3              cognitivemodels_0.0.10 testthat_2.3.2                         
    [4] data.table_1.13.0

**Comment by FlorianSchwendinger** [comment]
Hello Jana,

There is no ROI github since the project is hosted on R-Forge
https://r-forge.r-project.org/projects/roi/
an R specific predecessor of github.
You best reach me (and most of the R developers I know) if you just write an E-Mail.
FlorianSchwendinger at gmx.at

I see where the error occurs. But I have to think about potential implications and where to change it.

Best,
Florian
