### ISSUE TITLE
Where can we open issues for ROI package (R version)?

### ISSUE THREAD

**Issue by GitHunter0** [FlorianSchwendinger/ROI_docs#6]
Hi @FlorianSchwendinger , is here the right place to open issues of R's ROI package? 

The CRAN page of ROI package does display the GitHub link of the project. 

ROI is a package of central importance to R and I'm having some problems with it, so it would be really helpful to find the right place to share it.

I really appreciate if you can provide that information

**Comment by FlorianSchwendinger** [comment]
@"Hi @FlorianSchwendinger , is here the right place to open issues of R's ROI package?"
No this repo is only if you want to contribute to the documentation.

@"The CRAN page of ROI package does display the GitHub link of the project."
On https://cran.r-project.org/package=ROI I only see
http://roi.r-forge.r-project.org/ and https://r-forge.r-project.org/projects/roi/
which are the official project pages.

@"ROI is a package of central importance to R and I'm having some problems with it, so it would be really helpful to find the right place to share it."
The typicall way to communicate with package maintainers is to write an e-mail to the maintainers.
